### ISSUE TITLE
无法运行production模式

### ISSUE THREAD

**Issue by nogoodwh** [aqiongbei/buy_pig_plan#14]
你好，
       我在使用你的代码时出现了问题，想麻烦你能抽空帮我解决一下。
       当我在用production模式运行你的程序时，一直没反应，我不得不中止这个批处理：

D:\project\buy_pig_plan-master>npm start

> buy_pig_plan@1.0.0 start D:\project\buy_pig_plan-master
> cross-env NODE_ENV=production node app.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode
i got SIGINT
终止批处理操作吗(Y/N)? y

运行情况是以上这样的，我用debug模式运行就是正常的：

==================TASK TIMES: 1==================
TASK INFO: WEB NAME: 徐州市建筑工人医院 WEB TYPE: baidu_lxb
TASK RESULT: STATUS: failed MSG:[TIME OUT ERROR] TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
USED TIME: 30.013 S
SLEEP TIME: 0 S
==================TASK TIMES: 2==================
TASK INFO: WEB NAME: 浙江费玺尔流体设备有限公司 WEB TYPE: baidu_lxb
TASK RESULT: STATUS: failed MSG:[TIME OUT ERROR] TimeoutError: Navigation Timeout Exceeded: 30000ms exceeded
USED TIME: 30.004 S
SLEEP TIME: 0 S

只是网页一直都没响应而已（我估计这跟这些网页都不用了有关吧），因为我是nodejs 的萌新，请教一下大神，这个production模式下的问题应该怎么解决？

**Comment by aqiongbei** [comment]
production模式，非立即执行，是定时执行的

**Comment by nogoodwh** [comment]
是在default.json里进行修改的吧？
我是把代码改成了这样：
{
    "target": {
        "phone": "15878321990",
        "name": "adsf",
        "email": "505254110@qq.com",
        "address": "徐州",
        "comment": "菲律宾"
    },
    "attack": {
        "times": 100,
        "time": "0 0/2 * * * *",
        "web_type": "baidu_lxb",
        "task_type": "call", // "comment"
        "interval": 300000
    },
    "chromium": {
        "slowMo": 100,
        "timeout": 30000,
        "devtools": false,

    }
}
是不是time这里改一下：       "time": "0 0/2 * * * *",
这样就是每隔2分钟就执行一次了

**Comment by aqiongbei** [comment]
不要这么低频的跑，会出问题的。可能上次攻击没结束下一次攻击就开始了。
这个模式设计的最初目的是放在服务器跑的。并不是开放给个人机器使用的。
