### ISSUE TITLE
运行不了 报错

### ISSUE THREAD

**Issue by jieerps1994** [aqiongbei/buy_pig_plan#17]
/bomer/app.js:11
const {TASK_STATUS, ...util} = require('./utils/util');
                    ^^^

SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.runMain (module.js:611:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:160:9)

npm ERR! Linux 3.10.0-1062.1.2.el7.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.17.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! buy_pig_plan@1.0.0 start: `cross-env NODE_ENV=production node app.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the buy_pig_plan@1.0.0 start script 'cross-env NODE_ENV=production node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buy_pig_plan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buy_pig_plan
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buy_pig_plan
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /bomer/npm-debug.log

**Comment by aqiongbei** [comment]
你的node版本太低了，不支持ES6语法，升到高级的node就能用了。8.0+就可以了。
