### ISSUE TITLE
找不到输入框

### ISSUE THREAD

**Issue by starInEcust** [aqiongbei/buy_pig_plan#20]
我仔细观察了一下你的代码，先在config里加一个production.json。然后根据node-cron设置一下时间间隔，接下来应该是用一些在百度打广告的地址进行回拨。然后问题就来了- -， 没有这个class。会不会是这个输入框是异步加载的？还是百度改代码了
TASK RESULT: STATUS: failed MSG:[TYPE ERROR] Error: No node found for selector: .lxb-cb-input

**Comment by starInEcust** [comment]
使用baidu_lxb_50000.json里的地址，然后document.querySelector('.lxb-cb-input')，确实也没有这个元素

**Comment by starInEcust** [comment]
document.querySelectorAll('.nb-nodeboard-input') 这个元素大概10个网站里里面有3个，可以输入电话。

**Comment by QiuYukang** [comment]
> document.querySelectorAll

请问下应该怎么改呢
