### ISSUE TITLE
Production问题

### ISSUE THREAD

**Issue by FoxMiaoMai** [aqiongbei/buy_pig_plan#23]
npm start

> buy_pig_plan@1.0.0 start /Users/miaomai/Downloads/buy_pig_plan-master
> cross-env NODE_ENV=production node app.js

WARNING: NODE_ENV value of 'production' did not match any deployment config file names.
WARNING: See https://github.com/lorenwest/node-config/wiki/Strict-Mode

**Comment by kdmj** [comment]
怎么解决呢

**Comment by StrChangAn** [comment]
你用的是npm start ，用npm run debug试试

**Comment by HelloWorldFeng** [comment]
return dir[rnd].replace('.json', '');
                    ^

TypeError: Cannot read property 'replace' of undefined
    at getFilename (E:\Google\买猪计划\buy_pig_plan-master\utils\util.js:31:21)
    at Object.getURLList (E:\Google\买猪计划\buy_pig_plan-master\utils\util.js:20:20)
    at Object.<anonymous> (E:\Google\买猪计划\buy_pig_plan-master\app.js:17:33)

**Comment by HelloWorldFeng** [comment]
comment下报的
