### ISSUE TITLE
官网有验证码了

### ISSUE THREAD

**Issue by taozhiyu** [aqiongbei/buy_pig_plan#28]
官网开启了验证码。
应该是没有对验证码判断吧。。。
现在失效了
此外，我开了天翼防骚扰。。。。
手动随机测试10个，一个都没有接到

**Comment by kdmj** [comment]
是用npm start测试的还是debug呢
另外NODE_ENV的值'{NODE_ENV}'与任何部署配置文件名都不匹配。这个怎么解决呢
