### ISSUE TITLE
运行不了

### ISSUE THREAD

**Issue by leeschan** [aqiongbei/buy_pig_plan#6]
> buy_pig_plan@1.0.0 start /root/bomer
> cross-env NODE_ENV=production node app.js

sh: cross-env: command not found

npm ERR! Linux 5.0.0-1.el7.elrepo.x86_64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v6.16.0
npm ERR! npm  v3.10.10
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! buy_pig_plan@1.0.0 start: `cross-env NODE_ENV=production node app.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the buy_pig_plan@1.0.0 start script 'cross-env NODE_ENV=production node app.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the buy_pig_plan package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node app.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs buy_pig_plan
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls buy_pig_plan
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     /root/bomer/npm-debug.log

**Comment by smkw33d** [comment]
依赖没有装。
`npm config set puppeteer_download_host=https://npm.taobao.org/mirrors
npm install`

**Comment by kdmj** [comment]
NODE_ENV的值'{NODE_ENV}'与任何部署配置文件名都不匹配该怎么解决呢
能直接告诉我下解决方法吗

**Comment by kdmj** [comment]
NODE_ENV的值'{NODE_ENV}'与任何部署配置文件名都不匹配该怎么解决呢
能直接告诉我下解决方法吗

**Comment by kdmj** [comment]
> 依赖没有装。
> `npm config set puppeteer_download_host=https://npm.taobao.org/mirrors`
> `npm install`
NODE_ENV的值'{NODE_ENV}'与任何部署配置文件名都不匹配该怎么解决呢
能直接告诉我下解决方法吗
