### ISSUE TITLE
添加了淘宝镜像源，运行还是报错求解，这种情况该怎么办呀

### ISSUE THREAD

**Issue by 15991963047** [aqiongbei/buy_pig_plan#7]
C:\Users\Administrator\Desktop\buy_pig_plan-master>npm install
audited 1172 packages in 4.679s
found 0 vulnerabilities

C:\Users\Administrator\Desktop\buy_pig_plan-master>npm run debug

> buy_pig_plan@1.0.0 debug C:\Users\Administrator\Desktop\buy_pig_plan-master
> cross-env NODE_ENV=debug node app.js

Config {
  target:
   { phone: '18066820521',
     name: 'adsf',
     email: '908424842@qq.com',
     address: '西安',
     comment: '阿斯蒂芬' },
  attack:
   { times: 100,
     time: '0 2 * * * *',
     web_type: 'baidu_lxb',
     task_type: 'call',
     interval: 6000 },
  chromium:
   { slowMo: 100, timeout: 30000, devtools: false, headless: false } }
Error: Chromium revision is not downloaded. Run "npm install" or "yarn install"
    at Launcher.launch (C:\Users\Administrator\Desktop\buy_pig_plan-master\node
modules\puppeteer\lib\Launcher.js:119:15)
![image](https://user-images.githubusercontent.com/33410713/57534156-f9be2e80-7371-11e9-9d58-817e2fb5e95c.png)

**Comment by aqiongbei** [comment]
尝试删除已经安装的package，然后重新安装。
